### PR TITLE
Update deckgl to 8.1.5 version

### PR DESCRIPTION
**Pull request by manmorjim**
The version `8.1.5` fixes the [clipping issue](https://github.com/visgl/deck.gl/issues/4549)

image

### CODE REVIEW

**Review by alasarr — DISMISSED** [review]

**Review by alasarr — CHANGES_REQUESTED** [review]
Building is not working with this update

**Comment by manmorjim** [comment]
The build was failing due to the typescript version `3.9.2` has a bug https://github.com/microsoft/TypeScript/issues/38535 

I've fixed the version `3.8.3` which is prior to `3.9.2`.

**Review by VictorVelarde — CHANGES_REQUESTED** [review]
Nice fix!

Apply the TS update also to each package, please. So all of them have the same pinned version. Once that's done, we can merge this

**Comment by manmorjim** [comment]
TS version updated and pinned for all packages.

I've also updated all examples to use deckgl `8.1.5`

**Review by alasarr — APPROVED** [review]

**Comment by VictorVelarde** [comment]
@manmorjim Hey, I was also checking / updating the examples and we need to update ALL deck.gl components to 8.1.5 in package.json files (luma, geo-layers, etc) because otherwise the examples will fail

**Comment by manmorjim** [comment]
> @manmorjim Hey, I was also checking / updating the examples and we need to update ALL deck.gl components to 8.1.5 in package.json files (luma, geo-layers, etc) because otherwise the examples will fail

All deckgl components were updated to `8.1.5` except lumaGL due to deckgl `8.1.5` uses lumaGL version `8.1.2`.

**Review by VictorVelarde — APPROVED** [review]

**Comment by VictorVelarde** [comment]
Don't merge this please, I would mix this with my PR on examples

**Comment by VictorVelarde** [comment]
Done in https://github.com/CartoDB/toolkit/pull/110

**Pull request closed without merging**
